---
role_onprem: true
wireguard_manage: true
failover_core_manage: true

# --- overrides for full stack test ---
docker_manage: true
containers_manage: true
containers_start: true
containers_enabled:
  - minecraft
  - valheim
  - 7dtd
  - web_portal
  - player_monitor
web_portal_admin_enable: true
web_portal_admin_allow_cidrs:
  - 10.100.0.0/24
  - 10.0.0.0/24
  - 192.168.1.0/24
backups_manage: false

# docker compose fallback
containers_compose_cmd: "docker compose"
docker_packages:
  - docker.io
  - docker-compose

resolvconf_manage: true
resolvconf_nameservers:
  - 1.1.1.1
  - 8.8.8.8
