---
role_vps: true
wireguard_manage: true
wireguard_update_cache: false
base_update_cache: false
frr_manage: true
frr_require_vars: true
suricata_manage: true
suricata_require_vars: true
suricata_manage_service: true
suricata_interface: "ens3"
cloudflared_manage: true
cloudflared_require_vars: true
cloudflared_manage_service: true
cloudflared_restart_on_change: true
cloudflared_install_if_missing: true
portctl_manage: true
portctl_manage_service: true
portctl_restart_on_change: true
portctl_allow_overwrite: true
resolvconf_manage: true
resolvconf_nameservers:
  - 1.1.1.1
  - 8.8.8.8

# --- overrides for full stack test ---
ddos_notify_manage: true
ddos_notify_primary_ip: "10.100.0.2"
ddos_notify_port: 9001
portctl_default_dest_ip: "10.100.0.2"
portctl_ufw_rules:
  - "allow 22/tcp"
  - "allow 51820/udp"
  - "allow 25565/tcp"
  - "allow 19132/udp"
  - "allow 19133/udp"
  - "allow 2456/udp"
  - "allow 2457/udp"
  - "allow 2458/udp"
  - "allow 26900/udp"
  - "allow 26901/udp"
  - "allow 26902/udp"
portctl_forward_rules:
  - protocol: "tcp"
    ext_port: "25565"
    dest_ip: "10.100.0.2"
    dest_port: "25565"
  - protocol: "udp"
    ext_port: "19132"
    dest_ip: "10.100.0.2"
    dest_port: "19132"
  - protocol: "udp"
    ext_port: "19133"
    dest_ip: "10.100.0.2"
    dest_port: "19133"
  - protocol: "udp"
    ext_port: "2456"
    dest_ip: "10.100.0.2"
    dest_port: "2456"
  - protocol: "udp"
    ext_port: "2457"
    dest_ip: "10.100.0.2"
    dest_port: "2457"
  - protocol: "udp"
    ext_port: "2458"
    dest_ip: "10.100.0.2"
    dest_port: "2458"
  - protocol: "udp"
    ext_port: "26900"
    dest_ip: "10.100.0.2"
    dest_port: "26900"
  - protocol: "udp"
    ext_port: "26901"
    dest_ip: "10.100.0.2"
    dest_port: "26901"
  - protocol: "udp"
    ext_port: "26902"
    dest_ip: "10.100.0.2"
    dest_port: "26902"
frr_allow_overwrite: true
