---
role_vps: true
wireguard_manage: true
wireguard_update_cache: false
base_update_cache: false
frr_manage: true
frr_require_vars: true
suricata_manage: true
suricata_require_vars: true
suricata_manage_service: true
suricata_interface: "ens3"
cloudflared_manage: true
cloudflared_require_vars: true
cloudflared_manage_service: true
cloudflared_restart_on_change: true
cloudflared_install_if_missing: true
portctl_manage: true
portctl_manage_service: true
portctl_restart_on_change: true
portctl_allow_overwrite: true
resolvconf_manage: true
resolvconf_nameservers:
  - 1.1.1.1
  - 8.8.8.8

frr_allow_overwrite: true
