---
portctl_manage: false
portctl_manage_service: true
portctl_install_if_missing: true
portctl_update_cache: true
portctl_allow_overwrite: false
portctl_restart_on_change: true
portctl_apply_rules: true

portctl_packages:
  - python3
  - php-cli
  - ufw

portctl_agent_path: /opt/portctl/agent.py
portctl_rules_path: /opt/portctl/rules.json
portctl_config_path: /etc/portctl/config.json
portctl_default_dest_ip: "10.100.0.2"
portctl_public_interface: ""
portctl_ufw_rules: []
portctl_forward_rules: []

portctl_web_root: /srv/portctl-web
portctl_web_port: 9000
portctl_web_wg_bind: "10.100.0.1"
portctl_web_local_bind: "127.0.0.1"
portctl_wg_service: "wg-quick@wg0.service"
portctl_enable_web_wg: true
portctl_enable_web_local: true

portctl_service_name: portctl
portctl_web_service_name: portctl-web
portctl_web_local_service_name: portctl-web-local
portctl_service_state: started
portctl_web_service_state: started
portctl_web_local_service_state: started
